name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: "yarn"

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Generating HTML from my AsyncAPI document
        uses: docker://asyncapi/github-action-for-generator:2.1.12
        with:
          template: "@asyncapi/html-template@0.28.3"
          filepath: asyncapi/asyncapi.yml
          output: generated-docs/asyncapi

      - name: Make Json Schemas available
        run: cp -r generated-docs/asyncapi packages/web/public/api
        shell: bash

      - name: Install, build, and upload your site
        uses: withastro/action@v0
        with:
          path: ./packages/web
          package-manager: yarn

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
